---
langs: [fr_FR,en_US,es_ES,de_DE] 
baseurl: "/"
sass:
  sass_dir: assets/css
  style: compressed
markdown: kramdown
permalink: /404.html
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
gems:
- jekyll-paginate
- jekyll-seo-tag
exclude:
- vendor
plugins:
- jekyll-seo-tag
title: "Documentation Mystrom Jeedom Plugin"
description: "Ceci est la documentationdu plugin Mystrom pour Jeedom"
author: "Coolweb"
image: https://www.jeedom.com/site/logo.png